-- MySQL Script generated by MySQL Workbench
-- Wednesday 14 April 2021 03:15:55 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `id_customer` INT NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(20) NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `profile_image` BLOB NULL,
  PRIMARY KEY (`id_customer`),
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `id_customer_UNIQUE` (`id_customer` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`location` (
  `id_location` INT NOT NULL,
  `latitude` INT NOT NULL,
  `longitude` INT NOT NULL,
  PRIMARY KEY (`id_location`));


-- -----------------------------------------------------
-- Table `mydb`.`restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`restaurant` (
  `id_restaurant` INT NOT NULL,
  `restaurant_name` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `restaurant_image` LONGBLOB NULL,
  PRIMARY KEY (`id_restaurant`));


-- -----------------------------------------------------
-- Table `mydb`.`placeOrder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`placeOrder` (
  `id_place_order` INT NOT NULL,
  `order_time` DATETIME NOT NULL,
  `restaurant_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `price` FLOAT NOT NULL,
  `comment` VARCHAR(255) NULL,
  PRIMARY KEY (`id_place_order`),
  INDEX `fk_PlaceOrder_Restaurant1_idx` (`restaurant_id` ASC) VISIBLE,
  INDEX `fk_PlaceOrder_Customer1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_PlaceOrder_Restaurant1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `mydb`.`restaurant` (`id_restaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PlaceOrder_Customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `id_category` INT NOT NULL,
  `category_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_category`));


-- -----------------------------------------------------
-- Table `mydb`.`foodItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`foodItem` (
  `item_id` INT NOT NULL,
  `item_name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  `id_category` INT NOT NULL,
  `price` FLOAT NOT NULL,
  `is_veg` TINYINT NOT NULL,
  `id_restaurant` INT NOT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_MenuItem_Category1_idx` (`id_category` ASC) VISIBLE,
  INDEX `fk_FoodItem_Restaurant1_idx` (`id_restaurant` ASC) VISIBLE,
  CONSTRAINT `fk_MenuItem_Category1`
    FOREIGN KEY (`id_category`)
    REFERENCES `mydb`.`category` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FoodItem_Restaurant1`
    FOREIGN KEY (`id_restaurant`)
    REFERENCES `mydb`.`restaurant` (`id_restaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`inOrder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inOrder` (
  `id_in_order` INT NOT NULL,
  `PlaceOrder_id` INT NOT NULL,
  `Food_item_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`id_in_order`),
  INDEX `fk_InOrder_PlaceOrder1_idx` (`PlaceOrder_id` ASC) VISIBLE,
  INDEX `fk_InOrder_MenuItem1_idx` (`Food_item_id` ASC) VISIBLE,
  CONSTRAINT `fk_InOrder_PlaceOrder1`
    FOREIGN KEY (`PlaceOrder_id`)
    REFERENCES `mydb`.`placeOrder` (`id_place_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_InOrder_MenuItem1`
    FOREIGN KEY (`Food_item_id`)
    REFERENCES `mydb`.`foodItem` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`review` (
  `id_review` INT NOT NULL,
  `id_customer` INT NOT NULL,
  `item_id` INT NOT NULL,
  `rating` INT NULL,
  `comment` VARCHAR(255) NULL,
  PRIMARY KEY (`id_review`),
  INDEX `fk_Review_Customer1_idx` (`id_customer` ASC) VISIBLE,
  INDEX `fk_Review_MenuItem1_idx` (`item_id` ASC) VISIBLE,
  CONSTRAINT `fk_Review_Customer1`
    FOREIGN KEY (`id_customer`)
    REFERENCES `mydb`.`customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Review_MenuItem1`
    FOREIGN KEY (`item_id`)
    REFERENCES `mydb`.`foodItem` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`locationHasCustomer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`locationHasCustomer` (
  `id_location` INT NOT NULL,
  `id_customer` INT NOT NULL,
  PRIMARY KEY (`id_location`, `id_customer`),
  INDEX `fk_Location_has_Customer_Customer1_idx` (`id_customer` ASC) VISIBLE,
  INDEX `fk_Location_has_Customer_Location1_idx` (`id_location` ASC) VISIBLE,
  CONSTRAINT `fk_Location_has_Customer_Location1`
    FOREIGN KEY (`id_location`)
    REFERENCES `mydb`.`location` (`id_location`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Location_has_Customer_Customer1`
    FOREIGN KEY (`id_customer`)
    REFERENCES `mydb`.`customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`locationHasRestaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`locationHasRestaurant` (
  `Location_idLocation` INT NOT NULL,
  `id_restaurant` INT NOT NULL,
  PRIMARY KEY (`id_restaurant`, `Location_idLocation`),
  INDEX `fk_Location_has_Restaurant_Location1_idx` (`Location_idLocation` ASC) VISIBLE,
  INDEX `fk_LocationHasRestaurant_Restaurant1_idx` (`id_restaurant` ASC) VISIBLE,
  CONSTRAINT `fk_Location_has_Restaurant_Location1`
    FOREIGN KEY (`Location_idLocation`)
    REFERENCES `mydb`.`location` (`id_location`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LocationHasRestaurant_Restaurant1`
    FOREIGN KEY (`id_restaurant`)
    REFERENCES `mydb`.`restaurant` (`id_restaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
