-- MySQL Script generated by MySQL Workbench
-- Tuesday 13 April 2021 10:49:23 AM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema zomatodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zomatodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zomatodb` DEFAULT CHARACTER SET utf8 ;
USE `zomatodb` ;
-- MySQL Script generated by MySQL Workbench
-- Tuesday 13 April 2021 10:49:23 AM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `zomatodb`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zomatodb`.`City` (
  `id_city` INT NOT NULL,
  `city_name` VARCHAR(45) NULL,
  `zip_code` INT NULL,
  PRIMARY KEY (`id_city`));


-- -----------------------------------------------------
-- Table `zomatodb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zomatodb`.`Customer` (
  `id_customer` INT NOT NULL,
  `customer_name` VARCHAR(45) NULL,
  `address` VARCHAR(255) NULL,
  `phone_number` VARCHAR(10) NULL,
  `email` VARCHAR(20) NULL,
  `password` VARCHAR(45) NULL,
  `city_id` INT NOT NULL,
  `profile_image` BLOB NULL,
  PRIMARY KEY (`id_customer`),
  INDEX `fk_Customer_City_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_City`
    FOREIGN KEY (`city_id`)
    REFERENCES `zomatodb`.`City` (`id_city`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `zomatodb`.`Restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zomatodb`.`Restaurant` (
  `id_restaurant` INT NOT NULL,
  `city_id` INT NOT NULL,
  `address` VARCHAR(45) NULL,
  `restaurant_name` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `restaurant_image` LONGBLOB NULL,
  `RestaurantMenu_id` INT NOT NULL,
  PRIMARY KEY (`id_restaurant`),
  INDEX `fk_Resturant_City1_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `fk_Resturant_City1`
    FOREIGN KEY (`city_id`)
    REFERENCES `zomatodb`.`City` (`id_city`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `zomatodb`.`PlaceOrder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zomatodb`.`PlaceOrder` (
  `id_place_order` INT NOT NULL,
  `order_time` DATETIME NULL,
  `retaurant_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `price` INT NULL,
  `comment` VARCHAR(255) NULL,
  `address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_place_order`),
  INDEX `fk_PlaceOrder_Restaurant1_idx` (`retaurant_id` ASC) VISIBLE,
  INDEX `fk_PlaceOrder_Customer1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_PlaceOrder_Restaurant1`
    FOREIGN KEY (`retaurant_id`)
    REFERENCES `zomatodb`.`Restaurant` (`id_restaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PlaceOrder_Customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `zomatodb`.`Customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `zomatodb`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zomatodb`.`Category` (
  `id_category` INT NOT NULL,
  `category_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_category`));


-- -----------------------------------------------------
-- Table `zomatodb`.`FoodItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zomatodb`.`FoodItem` (
  `item_id` INT NOT NULL,
  `item_name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `id_category` INT NOT NULL,
  `price` INT NULL,
  `is_veg` INT NULL,
  `RestaurantMenu_id` INT NOT NULL,
  `Restaurant_id_restaurant` INT NOT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_MenuItem_Category1_idx` (`id_category` ASC) VISIBLE,
  INDEX `fk_FoodItem_Restaurant1_idx` (`Restaurant_id_restaurant` ASC) VISIBLE,
  CONSTRAINT `fk_MenuItem_Category1`
    FOREIGN KEY (`id_category`)
    REFERENCES `zomatodb`.`Category` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FoodItem_Restaurant1`
    FOREIGN KEY (`Restaurant_id_restaurant`)
    REFERENCES `zomatodb`.`Restaurant` (`id_restaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `zomatodb`.`InOrder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zomatodb`.`InOrder` (
  `id_in_order` INT NOT NULL,
  `PlaceOrder_id` INT NOT NULL,
  `Food_item_id` INT NOT NULL,
  `quantity` INT NULL,
  `price` INT NULL,
  PRIMARY KEY (`id_in_order`),
  INDEX `fk_InOrder_PlaceOrder1_idx` (`PlaceOrder_id` ASC) VISIBLE,
  INDEX `fk_InOrder_MenuItem1_idx` (`Food_item_id` ASC) VISIBLE,
  CONSTRAINT `fk_InOrder_PlaceOrder1`
    FOREIGN KEY (`PlaceOrder_id`)
    REFERENCES `zomatodb`.`PlaceOrder` (`id_place_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_InOrder_MenuItem1`
    FOREIGN KEY (`Food_item_id`)
    REFERENCES `zomatodb`.`FoodItem` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `zomatodb`.`Review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zomatodb`.`Review` (
  `id_review` INT NOT NULL,
  `id_customer` INT NOT NULL,
  `item_id` INT NOT NULL,
  `rating` INT NULL,
  `comment` VARCHAR(255) NULL,
  PRIMARY KEY (`id_review`),
  INDEX `fk_Review_Customer1_idx` (`id_customer` ASC) VISIBLE,
  INDEX `fk_Review_MenuItem1_idx` (`item_id` ASC) VISIBLE,
  CONSTRAINT `fk_Review_Customer1`
    FOREIGN KEY (`id_customer`)
    REFERENCES `zomatodb`.`Customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Review_MenuItem1`
    FOREIGN KEY (`item_id`)
    REFERENCES `zomatodb`.`FoodItem` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `zomatodb`.`FavoriteFood`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zomatodb`.`FavoriteFood` (
  `id_fav_food` INT NOT NULL,
  `id_customer` INT NOT NULL,
  `food_item_id` INT NOT NULL,
  PRIMARY KEY (`id_fav_food`),
  INDEX `fk_FavoriteFood_Customer1_idx` (`id_customer` ASC) VISIBLE,
  INDEX `fk_FavoriteFood_MenuItem1_idx` (`food_item_id` ASC) VISIBLE,
  CONSTRAINT `fk_FavoriteFood_Customer1`
    FOREIGN KEY (`id_customer`)
    REFERENCES `zomatodb`.`Customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FavoriteFood_MenuItem1`
    FOREIGN KEY (`food_item_id`)
    REFERENCES `zomatodb`.`FoodItem` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
