 CREATE TABLE IF NOT EXISTS `category` (`id_category` INTEGER NOT NULL auto_increment , `category_name` VARCHAR(255) NOT NULL, PRIMARY KEY (`id_category`)) ENGINE=InnoDB;
 SHOW INDEX FROM `category`
 CREATE TABLE IF NOT EXISTS `customer` (`id_customer` INTEGER NOT NULL auto_increment , `customer_name` VARCHAR(255) NOT NULL, `phone_number` VARCHAR(20), `email` VARCHAR(255) NOT NULL, `password` VARCHAR(255) NOT NULL, `profile_image` VARCHAR(1000), UNIQUE `phone_number_UNIQUE` (`phone_number`), UNIQUE `email_UNIQUE` (`email`), PRIMARY KEY (`id_customer`)) ENGINE=InnoDB;
 SHOW INDEX FROM `customer`
 CREATE TABLE IF NOT EXISTS `restaurant` (`id_restaurant` INTEGER NOT NULL auto_increment , `restaurant_name` VARCHAR(255) NOT NULL, `phone_number` VARCHAR(20) NOT NULL, `description` VARCHAR(255), `email` VARCHAR(255) NOT NULL UNIQUE, `restaurant_image` VARCHAR(1000), `city_name` VARCHAR(255) NOT NULL, PRIMARY KEY (`id_restaurant`)) ENGINE=InnoDB;
 SHOW INDEX FROM `restaurant`
 CREATE TABLE IF NOT EXISTS `foodItem` (`item_id` INTEGER NOT NULL auto_increment , `item_name` VARCHAR(255) NOT NULL, `description` VARCHAR(255), `id_category` INTEGER NOT NULL, `price` FLOAT NOT NULL, `is_veg` TINYINT NOT NULL, `id_restaurant` INTEGER NOT NULL, `item_image` VARCHAR(1000) NOT NULL, PRIMARY KEY (`item_id`), FOREIGN KEY (`id_category`) REFERENCES `category` (`id_category`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`id_restaurant`) REFERENCES `restaurant` (`id_restaurant`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
 SHOW INDEX FROM `foodItem`
 CREATE TABLE IF NOT EXISTS `placeOrder` (`id_place_order` INTEGER NOT NULL auto_increment , `order_time` DATETIME NOT NULL, `restaurant_id` INTEGER NOT NULL, `customer_id` INTEGER NOT NULL, `price` FLOAT NOT NULL, `comment` VARCHAR(255), PRIMARY KEY (`id_place_order`), FOREIGN KEY (`restaurant_id`) REFERENCES `restaurant` (`id_restaurant`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`customer_id`) REFERENCES `customer` (`id_customer`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
 SHOW INDEX FROM `placeOrder`
 CREATE TABLE IF NOT EXISTS `inOrder` (`id_in_order` INTEGER NOT NULL auto_increment , `PlaceOrder_id` INTEGER NOT NULL, `Food_item_id` INTEGER NOT NULL, `quantity` INTEGER NOT NULL, `price` FLOAT NOT NULL, PRIMARY KEY (`id_in_order`), FOREIGN KEY (`PlaceOrder_id`) REFERENCES `placeOrder` (`id_place_order`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`Food_item_id`) REFERENCES `foodItem` (`item_id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
 SHOW INDEX FROM `inOrder`
 CREATE TABLE IF NOT EXISTS `location` (`id_location` INTEGER NOT NULL auto_increment , `latitude` DOUBLE PRECISION NOT NULL, `longitude` DOUBLE PRECISION NOT NULL, PRIMARY KEY (`id_location`)) ENGINE=InnoDB;
 SHOW INDEX FROM `location`
 CREATE TABLE IF NOT EXISTS `locationHasCustomer` (`id_location` INTEGER NOT NULL , `id_customer` INTEGER NOT NULL , UNIQUE `locationHasCustomer_id_location_id_customer_unique` (`id_location`, `id_customer`), PRIMARY KEY (`id_location`, `id_customer`), FOREIGN KEY (`id_location`) REFERENCES `location` (`id_location`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`id_customer`) REFERENCES `customer` (`id_customer`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
 SHOW INDEX FROM `locationHasCustomer`
 CREATE TABLE IF NOT EXISTS `locationHasRestaurant` (`Location_idLocation` INTEGER NOT NULL , `id_restaurant` INTEGER NOT NULL , UNIQUE `locationHasRestaurant_id_restaurant_Location_idLocation_unique` (`Location_idLocation`, `id_restaurant`), PRIMARY KEY (`Location_idLocation`, `id_restaurant`), FOREIGN KEY (`Location_idLocation`) REFERENCES `location` (`id_location`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`id_restaurant`) REFERENCES `restaurant` (`id_restaurant`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
 SHOW INDEX FROM `locationHasRestaurant`
 CREATE TABLE IF NOT EXISTS `review` (`id_review` INTEGER NOT NULL auto_increment , `id_customer` INTEGER NOT NULL, `item_id` INTEGER NOT NULL, `rating` INTEGER, `comment` VARCHAR(255), PRIMARY KEY (`id_review`), FOREIGN KEY (`id_customer`) REFERENCES `customer` (`id_customer`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`item_id`) REFERENCES `foodItem` (`item_id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
 SHOW INDEX FROM `review`
 SELECT `item_id`, `item_name`, `description`, `id_category`, `price`, `is_veg`, `id_restaurant`, `item_image` FROM `foodItem` AS `foodItem` WHERE `foodItem`.`id_restaurant` = 1;
 SELECT `restaurant`.`id_restaurant`, `restaurant`.`restaurant_name`, `restaurant`.`phone_number`, `restaurant`.`description`, `restaurant`.`email`, `restaurant`.`restaurant_image`, `restaurant`.`city_name`, `Location_idLocation_locations`.`id_location` AS `Location_idLocation_locations.id_location`, `Location_idLocation_locations`.`latitude` AS `Location_idLocation_locations.latitude`, `Location_idLocation_locations`.`longitude` AS `Location_idLocation_locations.longitude` FROM `restaurant` AS `restaurant` LEFT OUTER JOIN ( `locationHasRestaurant` AS `Location_idLocation_locations->locationHasRestaurant` INNER JOIN `location` AS `Location_idLocation_locations` ON `Location_idLocation_locations`.`id_location` = `Location_idLocation_locations->locationHasRestaurant`.`Location_idLocation`) ON `restaurant`.`id_restaurant` = `Location_idLocation_locations->locationHasRestaurant`.`id_restaurant` WHERE `restaurant`.`id_restaurant` = 1;
[nodemon] restarting due to changes...
[nodemon] starting `node server.js`
 CREATE TABLE IF NOT EXISTS `category` (`id_category` INTEGER NOT NULL auto_increment , `category_name` VARCHAR(255) NOT NULL, PRIMARY KEY (`id_category`)) ENGINE=InnoDB;
 SHOW INDEX FROM `category`
 CREATE TABLE IF NOT EXISTS `customer` (`id_customer` INTEGER NOT NULL auto_increment , `customer_name` VARCHAR(255) NOT NULL, `phone_number` VARCHAR(20), `email` VARCHAR(255) NOT NULL, `password` VARCHAR(255) NOT NULL, `profile_image` VARCHAR(1000), UNIQUE `phone_number_UNIQUE` (`phone_number`), UNIQUE `email_UNIQUE` (`email`), PRIMARY KEY (`id_customer`)) ENGINE=InnoDB;
 SHOW INDEX FROM `customer`
 CREATE TABLE IF NOT EXISTS `restaurant` (`id_restaurant` INTEGER NOT NULL auto_increment , `restaurant_name` VARCHAR(255) NOT NULL, `phone_number` VARCHAR(20) NOT NULL, `description` VARCHAR(255), `email` VARCHAR(255) NOT NULL UNIQUE, `restaurant_image` VARCHAR(1000), `city_name` VARCHAR(255) NOT NULL, PRIMARY KEY (`id_restaurant`)) ENGINE=InnoDB;
 SHOW INDEX FROM `restaurant`
 CREATE TABLE IF NOT EXISTS `foodItem` (`item_id` INTEGER NOT NULL auto_increment , `item_name` VARCHAR(255) NOT NULL, `description` VARCHAR(255), `id_category` INTEGER NOT NULL, `price` FLOAT NOT NULL, `is_veg` TINYINT NOT NULL, `id_restaurant` INTEGER NOT NULL, `item_image` VARCHAR(1000) NOT NULL, PRIMARY KEY (`item_id`), FOREIGN KEY (`id_category`) REFERENCES `category` (`id_category`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`id_restaurant`) REFERENCES `restaurant` (`id_restaurant`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
 SHOW INDEX FROM `foodItem`
 CREATE TABLE IF NOT EXISTS `placeOrder` (`id_place_order` INTEGER NOT NULL auto_increment , `order_time` DATETIME NOT NULL, `restaurant_id` INTEGER NOT NULL, `customer_id` INTEGER NOT NULL, `price` FLOAT NOT NULL, `comment` VARCHAR(255), PRIMARY KEY (`id_place_order`), FOREIGN KEY (`restaurant_id`) REFERENCES `restaurant` (`id_restaurant`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`customer_id`) REFERENCES `customer` (`id_customer`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
 SHOW INDEX FROM `placeOrder`
 CREATE TABLE IF NOT EXISTS `inOrder` (`id_in_order` INTEGER NOT NULL auto_increment , `PlaceOrder_id` INTEGER NOT NULL, `Food_item_id` INTEGER NOT NULL, `quantity` INTEGER NOT NULL, `price` FLOAT NOT NULL, PRIMARY KEY (`id_in_order`), FOREIGN KEY (`PlaceOrder_id`) REFERENCES `placeOrder` (`id_place_order`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`Food_item_id`) REFERENCES `foodItem` (`item_id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
 SHOW INDEX FROM `inOrder`
 CREATE TABLE IF NOT EXISTS `location` (`id_location` INTEGER NOT NULL auto_increment , `latitude` DOUBLE PRECISION NOT NULL, `longitude` DOUBLE PRECISION NOT NULL, PRIMARY KEY (`id_location`)) ENGINE=InnoDB;
 SHOW INDEX FROM `location`
 CREATE TABLE IF NOT EXISTS `locationHasCustomer` (`id_location` INTEGER NOT NULL , `id_customer` INTEGER NOT NULL , UNIQUE `locationHasCustomer_id_location_id_customer_unique` (`id_location`, `id_customer`), PRIMARY KEY (`id_location`, `id_customer`), FOREIGN KEY (`id_location`) REFERENCES `location` (`id_location`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`id_customer`) REFERENCES `customer` (`id_customer`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
 SHOW INDEX FROM `locationHasCustomer`
 CREATE TABLE IF NOT EXISTS `locationHasRestaurant` (`Location_idLocation` INTEGER NOT NULL , `id_restaurant` INTEGER NOT NULL , UNIQUE `locationHasRestaurant_id_restaurant_Location_idLocation_unique` (`Location_idLocation`, `id_restaurant`), PRIMARY KEY (`Location_idLocation`, `id_restaurant`), FOREIGN KEY (`Location_idLocation`) REFERENCES `location` (`id_location`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`id_restaurant`) REFERENCES `restaurant` (`id_restaurant`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
 SHOW INDEX FROM `locationHasRestaurant`
 CREATE TABLE IF NOT EXISTS `review` (`id_review` INTEGER NOT NULL auto_increment , `id_customer` INTEGER NOT NULL, `item_id` INTEGER NOT NULL, `rating` INTEGER, `comment` VARCHAR(255), PRIMARY KEY (`id_review`), FOREIGN KEY (`id_customer`) REFERENCES `customer` (`id_customer`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`item_id`) REFERENCES `foodItem` (`item_id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
 SHOW INDEX FROM `review`