-- MySQL Workbench Synchronization
-- Generated: 2021-03-04 15:22
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Vivek
SET
  @OLD_UNIQUE_CHECKS = @ @UNIQUE_CHECKS,
  UNIQUE_CHECKS = 0;

SET
  @OLD_FOREIGN_KEY_CHECKS = @ @FOREIGN_KEY_CHECKS,
  FOREIGN_KEY_CHECKS = 0;

SET
  @OLD_SQL_MODE = @ @SQL_MODE,
  SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `mydb`.`Branch` (
  `Branch` INT(11) NOT NULL AUTO_INCREMENT,
  `Branch_Addr` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`Branch`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `mydb`.`Supply` (
  `Branch` INT(11) NOT NULL,
  `ISBN` INT(11) NOT NULL,
  `Num_copies` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Branch`, `ISBN`),
  UNIQUE INDEX `ISBN_UNIQUE` (`ISBN` ASC) VISIBLE,
  CONSTRAINT `fk_Supply_Branch` FOREIGN KEY (`Branch`) REFERENCES `mydb`.`Branch` (`Branch`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Supply_Book1` FOREIGN KEY (`ISBN`) REFERENCES `mydb`.`Book` (`ISBN`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `mydb`.`Book` (
  `ISBN` INT(11) NOT NULL,
  `Title` VARCHAR(100) NULL DEFAULT NULL,
  `Author` VARCHAR(100) NULL DEFAULT NULL,
  `Publisher` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ISBN`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

SET
  SQL_MODE = @OLD_SQL_MODE;

SET
  FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;

SET
  UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;



  -- MySQL Workbench Synchronization
-- Generated: 2021-03-04 16:55
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Vivek

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER TABLE `mydb`.`Supply` 
DROP FOREIGN KEY `fk_Supply_Book1`;

CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `idClient` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Location` VARCHAR(45) NULL DEFAULT NULL,
  `idManager` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idClient`),
  INDEX `fk_Client_Manager1_idx` (`idManager` ASC) VISIBLE,
  CONSTRAINT `fk_Client_Manager1`
    FOREIGN KEY (`idManager`)
    REFERENCES `mydb`.`Manager` (`idManager`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `mydb`.`Manager` (
  `idManager` INT(11) NOT NULL AUTO_INCREMENT,
  `Manager_Name` VARCHAR(45) NULL DEFAULT NULL,
  `Manager_Location` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idManager`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `mydb`.`Staff` (
  `idStaff` INT(11) NOT NULL,
  `Staff_Name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idStaff`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `mydb`.`Project` (
  `idStaff` INT(11) NOT NULL,
  `idContract` INT(11) NOT NULL,
  `Staff_Location` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idStaff`, `idContract`),
  INDEX `fk_Project_Contract1_idx` (`idContract` ASC) VISIBLE,
  CONSTRAINT `fk_Project_Staff1`
    FOREIGN KEY (`idStaff`)
    REFERENCES `mydb`.`Staff` (`idStaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Project_Contract1`
    FOREIGN KEY (`idContract`)
    REFERENCES `mydb`.`Contract` (`idContract`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `mydb`.`Contract` (
  `idContract` INT(11) NOT NULL,
  `idClient` INT(11) NULL DEFAULT NULL,
  `Estimated_Cost` INT(11) NULL DEFAULT NULL,
  `Completion_Date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idContract`),
  INDEX `fk_Contract_Client1_idx` (`idClient` ASC) VISIBLE,
  CONSTRAINT `fk_Contract_Client1`
    FOREIGN KEY (`idClient`)
    REFERENCES `mydb`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

ALTER TABLE `mydb`.`Supply` 
DROP FOREIGN KEY `fk_Supply_Branch`;

ALTER TABLE `mydb`.`Supply` ADD CONSTRAINT `fk_Supply_Branch`
  FOREIGN KEY (`Branch`)
  REFERENCES `mydb`.`Branch` (`Branch`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `fk_Supply_Book1`
  FOREIGN KEY (`ISBN`)
  REFERENCES `mydb`.`Book` (`ISBN`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


